### ISSUE TITLE
Connection aborted error 

### ISSUE THREAD

**Issue by ganeshrn** [ansible/ansible-ai-connect-service#31]
The stack trace is seen occasionally while using the service with the VSCode extension and it is not always reproducible.
Logs:
```
docker-compose-django-1  | Internal Server Error: /api/ai/completions/
docker-compose-django-1  | Traceback (most recent call last):
docker-compose-django-1  |   File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
docker-compose-django-1  |     httplib_response = self._make_request(
docker-compose-django-1  |   File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
docker-compose-django-1  |     six.raise_from(e, None)
docker-compose-django-1  |   File "<string>", line 3, in raise_from
docker-compose-django-1  |   File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
docker-compose-django-1  |     httplib_response = conn.getresponse()
docker-compose-django-1  |   File "/usr/lib64/python3.9/http/client.py", line 1377, in getresponse
docker-compose-django-1  |     response.begin()
docker-compose-django-1  |   File "/usr/lib64/python3.9/http/client.py", line 320, in begin
docker-compose-django-1  |     version, status, reason = self._read_status()
docker-compose-django-1  |   File "/usr/lib64/python3.9/http/client.py", line 281, in _read_status
docker-compose-django-1  |     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
docker-compose-django-1  |   File "/usr/lib64/python3.9/socket.py", line 704, in readinto
docker-compose-django-1  |     return self._sock.recv_into(b)
docker-compose-django-1  |   File "/usr/lib64/python3.9/ssl.py", line 1242, in recv_into
docker-compose-django-1  |     return self.read(nbytes, buffer)
docker-compose-django-1  |   File "/usr/lib64/python3.9/ssl.py", line 1100, in read
docker-compose-django-1  |     return self._sslobj.read(len, buffer)
docker-compose-django-1  | ConnectionResetError: [Errno 104] Connection reset by peer
docker-compose-django-1  | 
docker-compose-django-1  | During handling of the above exception, another exception occurred:
docker-compose-django-1  | 
docker-compose-django-1  | Traceback (most recent call last):
docker-compose-django-1  |   File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
docker-compose-django-1  |     resp = conn.urlopen(
docker-compose-django-1  |   File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
docker-compose-django-1  |     retries = retries.increment(
docker-compose-django-1  |   File "/usr/lib/python3.9/site-packages/urllib3/util/retry.py", line 532, in increment
docker-compose-django-1  |     raise six.reraise(type(error), error, _stacktrace)
docker-compose-django-1  |   File "/usr/lib/python3.9/site-packages/urllib3/packages/six.py", line 708, in reraise
docker-compose-django-1  |     raise value.with_traceback(tb)
docker-compose-django-1  |   File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
docker-compose-django-1  |     httplib_response = self._make_request(
docker-compose-django-1  |   File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
docker-compose-django-1  |     six.raise_from(e, None)
docker-compose-django-1  |   File "<string>", line 3, in raise_from
docker-compose-django-1  |   File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
docker-compose-django-1  |     httplib_response = conn.getresponse()
docker-compose-django-1  |   File "/usr/lib64/python3.9/http/client.py", line 1377, in getresponse
docker-compose-django-1  |     response.begin()
docker-compose-django-1  |   File "/usr/lib64/python3.9/http/client.py", line 320, in begin
docker-compose-django-1  |     version, status, reason = self._read_status()
docker-compose-django-1  |   File "/usr/lib64/python3.9/http/client.py", line 281, in _read_status
docker-compose-django-1  |     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
docker-compose-django-1  |   File "/usr/lib64/python3.9/socket.py", line 704, in readinto
docker-compose-django-1  |     return self._sock.recv_into(b)
docker-compose-django-1  |   File "/usr/lib64/python3.9/ssl.py", line 1242, in recv_into
docker-compose-django-1  |     return self.read(nbytes, buffer)
docker-compose-django-1  |   File "/usr/lib64/python3.9/ssl.py", line 1100, in read
docker-compose-django-1  |     return self._sslobj.read(len, buffer)
docker-compose-django-1  | urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
docker-compose-django-1  | 
docker-compose-django-1  | During handling of the above exception, another exception occurred:
docker-compose-django-1  | 
docker-compose-django-1  | Traceback (most recent call last):
docker-compose-django-1  |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
docker-compose-django-1  |     response = get_response(request)
docker-compose-django-1  |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
docker-compose-django-1  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
docker-compose-django-1  |   File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
docker-compose-django-1  |     return view_func(*args, **kwargs)
docker-compose-django-1  |   File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 103, in view
docker-compose-django-1  |     return self.dispatch(request, *args, **kwargs)
docker-compose-django-1  |   File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
docker-compose-django-1  |     response = self.handle_exception(exc)
docker-compose-django-1  |   File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
docker-compose-django-1  |     self.raise_uncaught_exception(exc)
docker-compose-django-1  |   File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
docker-compose-django-1  |     raise exc
docker-compose-django-1  |   File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
docker-compose-django-1  |     response = handler(request, *args, **kwargs)
docker-compose-django-1  |   File "/opt/ansible_wisdom/ai/api/views.py", line 31, in post
docker-compose-django-1  |     response = model_mesh_client.infer(data, model_name=model_name)
docker-compose-django-1  |   File "/opt/ansible_wisdom/ai/api/mode_mesh/http_client.py", line 21, in infer
docker-compose-django-1  |     result = self.session.post(self._prediction_url, headers=self.headers, json=model_input)
docker-compose-django-1  |   File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 590, in post
docker-compose-django-1  |     return self.request('POST', url, data=data, json=json, **kwargs)
docker-compose-django-1  |   File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
docker-compose-django-1  |     resp = self.send(prep, **send_kwargs)
docker-compose-django-1  |   File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
docker-compose-django-1  |     r = adapter.send(request, **kwargs)
docker-compose-django-1  |   File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 498, in send
docker-compose-django-1  |     raise ConnectionError(err, request=request)
docker-compose-django-1  | requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
docker-compose-django-1  | ERROR:Internal Server Error: /api/ai/completions/
docker-compose-django-1  | Traceback (most recent call last):
docker-compose-django-1  |   File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
docker-compose-django-1  |     httplib_response = self._make_request(
docker-compose-django-1  |   File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
docker-compose-django-1  |     six.raise_from(e, None)
docker-compose-django-1  |   File "<string>", line 3, in raise_from
docker-compose-django-1  |   File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
docker-compose-django-1  |     httplib_response = conn.getresponse()
docker-compose-django-1  |   File "/usr/lib64/python3.9/http/client.py", line 1377, in getresponse
docker-compose-django-1  |     response.begin()
docker-compose-django-1  |   File "/usr/lib64/python3.9/http/client.py", line 320, in begin
docker-compose-django-1  |     version, status, reason = self._read_status()
docker-compose-django-1  |   File "/usr/lib64/python3.9/http/client.py", line 281, in _read_status
docker-compose-django-1  |     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
docker-compose-django-1  |   File "/usr/lib64/python3.9/socket.py", line 704, in readinto
docker-compose-django-1  |     return self._sock.recv_into(b)
docker-compose-django-1  |   File "/usr/lib64/python3.9/ssl.py", line 1242, in recv_into
docker-compose-django-1  |     return self.read(nbytes, buffer)
docker-compose-django-1  |   File "/usr/lib64/python3.9/ssl.py", line 1100, in read
docker-compose-django-1  |     return self._sslobj.read(len, buffer)
docker-compose-django-1  | ConnectionResetError: [Errno 104] Connection reset by peer
docker-compose-django-1  | 
docker-compose-django-1  | During handling of the above exception, another exception occurred:
docker-compose-django-1  | 
docker-compose-django-1  | Traceback (most recent call last):
docker-compose-django-1  |   File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
docker-compose-django-1  |     resp = conn.urlopen(
docker-compose-django-1  |   File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
docker-compose-django-1  |     retries = retries.increment(
docker-compose-django-1  |   File "/usr/lib/python3.9/site-packages/urllib3/util/retry.py", line 532, in increment
docker-compose-django-1  |     raise six.reraise(type(error), error, _stacktrace)
docker-compose-django-1  |   File "/usr/lib/python3.9/site-packages/urllib3/packages/six.py", line 708, in reraise
docker-compose-django-1  |     raise value.with_traceback(tb)
docker-compose-django-1  |   File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
docker-compose-django-1  |     httplib_response = self._make_request(
docker-compose-django-1  |   File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
docker-compose-django-1  |     six.raise_from(e, None)
docker-compose-django-1  |   File "<string>", line 3, in raise_from
docker-compose-django-1  |   File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
docker-compose-django-1  |     httplib_response = conn.getresponse()
docker-compose-django-1  |   File "/usr/lib64/python3.9/http/client.py", line 1377, in getresponse
docker-compose-django-1  |     response.begin()
docker-compose-django-1  |   File "/usr/lib64/python3.9/http/client.py", line 320, in begin
docker-compose-django-1  |     version, status, reason = self._read_status()
docker-compose-django-1  |   File "/usr/lib64/python3.9/http/client.py", line 281, in _read_status
docker-compose-django-1  |     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
docker-compose-django-1  |   File "/usr/lib64/python3.9/socket.py", line 704, in readinto
docker-compose-django-1  |     return self._sock.recv_into(b)
docker-compose-django-1  |   File "/usr/lib64/python3.9/ssl.py", line 1242, in recv_into
docker-compose-django-1  |     return self.read(nbytes, buffer)
docker-compose-django-1  |   File "/usr/lib64/python3.9/ssl.py", line 1100, in read
docker-compose-django-1  |     return self._sslobj.read(len, buffer)
docker-compose-django-1  | urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
docker-compose-django-1  | 
docker-compose-django-1  | During handling of the above exception, another exception occurred:
docker-compose-django-1  | 
docker-compose-django-1  | Traceback (most recent call last):
docker-compose-django-1  |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
docker-compose-django-1  |     response = get_response(request)
docker-compose-django-1  |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
docker-compose-django-1  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
docker-compose-django-1  |   File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
docker-compose-django-1  |     return view_func(*args, **kwargs)
docker-compose-django-1  |   File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 103, in view
docker-compose-django-1  |     return self.dispatch(request, *args, **kwargs)
docker-compose-django-1  |   File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
docker-compose-django-1  |     response = self.handle_exception(exc)
docker-compose-django-1  |   File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
docker-compose-django-1  |     self.raise_uncaught_exception(exc)
docker-compose-django-1  |   File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
docker-compose-django-1  |     raise exc
docker-compose-django-1  |   File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
docker-compose-django-1  |     response = handler(request, *args, **kwargs)
docker-compose-django-1  |   File "/opt/ansible_wisdom/ai/api/views.py", line 31, in post
docker-compose-django-1  |     response = model_mesh_client.infer(data, model_name=model_name)
docker-compose-django-1  |   File "/opt/ansible_wisdom/ai/api/mode_mesh/http_client.py", line 21, in infer
docker-compose-django-1  |     result = self.session.post(self._prediction_url, headers=self.headers, json=model_input)
docker-compose-django-1  |   File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 590, in post
docker-compose-django-1  |     return self.request('POST', url, data=data, json=json, **kwargs)
docker-compose-django-1  |   File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
docker-compose-django-1  |     resp = self.send(prep, **send_kwargs)
docker-compose-django-1  |   File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
docker-compose-django-1  |     r = adapter.send(request, **kwargs)
docker-compose-django-1  |   File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 498, in send
docker-compose-django-1  |     raise ConnectionError(err, request=request)
docker-compose-django-1  | requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
docker-compose-django-1  | [23/Jan/2023 05:34:15] "POST /api/ai/completions/ HTTP/1.1" 500 229062
```

**Comment by gebhardtr** [comment]
closing, please reopen if you still see the issue and thanks again for opening it!
